services:
  - type: web
    name: telegram-translator-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: BOT_TOKEN
        value: 7608150428:AAHS-RBJXGaB6VZPo1WSHbR3RyibUhthUbE
